theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: DjangoForge - docs
description: A ready to deploy Django project
logo: "./assets/img/DjangoForge.png"
favicon: "./assets/img/djangoforgeico.svg"